apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: __TOKEN__
    apiServerEndpoint: "__ENDPOINT__"
    caCertHashes:
      - __CERT__
nodeRegistration:
  name: __NODE_NAME__
  kubeletExtraArgs:
    node-ip: __NODE_PRIVATE_IP__
